name: feelcare
description: A complete habit and mood tracker.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_messaging: ^15.0.0
  provider: ^6.1.2
  hive_flutter: ^1.1.0
  lottie: ^3.1.0
  fl_chart: ^0.66.0
  confetti: ^0.7.0
  shake: ^2.2.0
  local_auth: ^2.2.0
  table_calendar: ^3.1.0
  audioplayers: ^5.2.1
  url_launcher: ^6.2.5
  intl: ^0.19.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/dancer-woman.json
    - assets/lottie/fire heart.json
    - assets/lottie/loading refresh.json
    - assets/lottie/hi_stiker.json
    - assets/lottie/happy_sticker.json
    - assets/sounds/bahagia.mp3
    - assets/sounds/cakcakcekuk.mp3
    - assets/sounds/zootopia.mp3
    - assets/sounds/btob.mp3