name: feelcare
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # General range for Flutter 3.x to avoid constant updates

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_slidable: ^4.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_heatmap_calendar: ^1.0.5
  firebase_auth: ^5.6.0 # Keeping this version as it was, to resolve 'web' conflict by downgrading build_runner
  firebase_core: ^3.14.0 # Keeping this version as it was
  provider: ^6.1.1
  local_auth: ^2.2.0
  shared_preferences: ^2.2.3
  flutter_facebook_auth: ^7.1.2
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  firebase_storage: ^12.4.7
  cloud_firestore: 5.6.9 # <<< ADD THIS LINE
  table_calendar: ^3.0.9 # We'll need this later for the calendar
  flutter_local_notifications: ^17.0.0 # We'll need this later for notifications
  intl: ^0.20.2
  firebase_messaging: ^15.2.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.14 # Downgraded as suggested by the pub error message
  flutter_lints: 5.0.0

flutter:
  uses-material-design: true